version: '3.8'

services:
  api1: &api
    build: .
    environment:
      - NODE_ENV=production
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: '90MB'

  api2:
    <<: *api
    environment:
      - NODE_ENV=production
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: '90MB'

  redis:
    image: redis:7-alpine
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '50MB'

  nginx:
    image: nginx:alpine
    ports:
      - '9999:9999'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '15MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
